models:
  elasticnet:
    alpha: [0.001, 0.01, 0.1, 1.0]
    l1_ratio: [0.1, 0.5, 0.9]
    random_state: [42]

  randomforest:
    n_estimators: [100, 200, 500]
    max_depth: [5, 10, 20, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: ["sqrt", "log2", null]
    random_state: [42]

  xgbregressor:
    n_estimators: [100, 200, 500]
    learning_rate: [0.01, 0.05, 0.1]
    max_depth: [3, 5, 7]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    gamma: [0, 0.1, 0.2]
    reg_alpha: [0, 0.1, 1]
    reg_lambda: [0.5, 1.0, 2.0]
    random_state: [42]

model_evaluation:
  evaluation_metric: r2
  note: "Compare tuned models and pick best"
