artifacts_root: artifacts

# data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


# validation
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  status_file: status.txt
  report_file: report.yaml
  all_schema: schema.yaml


# data transformation
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv


# model trainer
model_trainer:
  root_dir: artifacts/model_trainer
  trained_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib


#model evaluation
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/randomforest.pkl
  metric_file_name: artifacts/model_evaluation/metric.json
  mlflow_url: https://dagshub.com/Francisroyce/End-to-End-ML-project-MLflow.mlflow



 
